# Generated by Django 3.0.8 on 2020-08-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_page',
        ),
    ]
