# Generated by Django 3.0.8 on 2020-08-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginpage', '0002_delete_login_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_pic', models.ImageField(blank=True, upload_to='Profile_pic')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
