# Generated by Django 3.0.8 on 2020-08-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_auto_20200825_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_page',
            name='created',
        ),
    ]
