# Generated by Django 3.0.8 on 2020-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0006_remove_login_page_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_page',
            name='something_about_yourself',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
