# Generated by Django 3.0.8 on 2020-08-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0007_login_page_something_about_yourself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_page',
            name='something_about_yourself',
        ),
    ]
